package Model;

import java.time.LocalDateTime;

/** Object model for appointments. */
public class Appointment {
  private int id, customerId, userId, contactId;
  private String title, description, location, type, createdBy, lastUpdatedBy;
  private LocalDateTime start, end, createDate, lastUpdate;

  /** Default constructor. */
  public Appointment(
      int id,
      int customerId,
      int userId,
      int contactId,
      String title,
      String description,
      String location,
      String type,
      LocalDateTime start,
      LocalDateTime end,
      LocalDateTime createDate,
      String createdBy,
      LocalDateTime lastUpdate,
      String lastUpdatedBy) {
    this.id = id;
    this.customerId = customerId;
    this.userId = userId;
    this.contactId = contactId;
    this.title = title;
    this.description = description;
    this.location = location;
    this.type = type;
    this.start = start;
    this.end = end;
    this.createDate = createDate;
    this.createdBy = createdBy;
    this.lastUpdate = lastUpdate;
    this.lastUpdatedBy = lastUpdatedBy;
  }

  /**
   * Constructor used in ModifyAppointmentController. Excludes attributes automatically generated by
   * the database.
   */
  public Appointment(
      int customerId,
      int userId,
      int contactId,
      String title,
      String description,
      String location,
      String type,
      LocalDateTime start,
      LocalDateTime end,
      String createdBy,
      String lastUpdatedBy) {
    this.customerId = customerId;
    this.userId = userId;
    this.contactId = contactId;
    this.title = title;
    this.description = description;
    this.location = location;
    this.type = type;
    this.start = start;
    this.end = end;
    this.createdBy = createdBy;
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public int getCustomerId() {
    return customerId;
  }

  public void setCustomerId(int customerId) {
    this.customerId = customerId;
  }

  public int getUserId() {
    return userId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

  public int getContactId() {
    return contactId;
  }

  public void setContactId(int contactId) {
    this.contactId = contactId;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public LocalDateTime getStart() {
    return start;
  }

  public void setStart(LocalDateTime start) {
    this.start = start;
  }

  public LocalDateTime getEnd() {
    return end;
  }

  public void setEnd(LocalDateTime end) {
    this.end = end;
  }

  public LocalDateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(LocalDateTime createDate) {
    this.createDate = createDate;
  }

  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public LocalDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(LocalDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }
}
