package Model;

/** Object model for customers. */
public class Customer {

  private int id, divisionId;
  private String name, address, postalCode, phone, createDate, createdBy, lastUpdate, lastUpdatedBy;

  /** Default constructor. */
  public Customer(
      int id,
      int divisionId,
      String name,
      String address,
      String postalCode,
      String phone,
      String createDate,
      String createdBy,
      String lastUpdate,
      String lastUpdatedBy) {
    this.id = id;
    this.divisionId = divisionId;
    this.name = name;
    this.address = address;
    this.postalCode = postalCode;
    this.phone = phone;
    this.createDate = createDate;
    this.createdBy = createdBy;
    this.lastUpdate = lastUpdate;
    this.lastUpdatedBy = lastUpdatedBy;
  }

  /**
   * Constructor used in ModifyCustomerController. Excludes attributes automatically generated by
   * the database.
   */
  public Customer(
      int divisionId,
      String name,
      String address,
      String postalCode,
      String phone,
      String createdBy,
      String lastUpdatedBy) {
    this.divisionId = divisionId;
    this.name = name;
    this.address = address;
    this.postalCode = postalCode;
    this.phone = phone;
    this.createdBy = createdBy;
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public int getDivisionId() {
    return divisionId;
  }

  public void setDivisionId(int divisionId) {
    this.divisionId = divisionId;
  }

  public String getName() {
    return name;
  }

  public void setName(String Name) {
    this.name = name;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public String getCreateDate() {
    return createDate;
  }

  public void setCreateDate(String createDate) {
    this.createDate = createDate;
  }

  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public String getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  /** Overrides string conversion for use in JavaFX elements. */
  @Override
  public String toString() {
    return (name);
  }
}
